#
# Infinix NOTE 23 (G99 / MT6789)
# Board configuration file
#
include vendor/ssh/NOTE_23/BoardConfigVendor.mk

BOARD_VENDOR := ssh
TARGET_BOARD_PLATFORM := mt6789
TARGET_ARCH := arm64
TARGET_KERNEL_ARCH := arm64

TARGET_CPU_ABI := arm64-v8a
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI_LIST := arm64-v8a armeabi-v7a
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a55
TARGET_SUPPORTS_64_BIT_APPS := true

#BOARD_VENDOR := ssh
#TARGET_BOARD_PLATFORM := mt6789
#TARGET_ARCH := arm64
#TARGET_KERNEL_ARCH := arm64

#TARGET_ARCH := arm64
#TARGET_ARCH_VARIANT := armv8-a
#TARGET_CPU_ABI := arm64-v8a
#TARGET_CPU_ABI2 := 
#TARGET_CPU_ABI_LIST := arm64-v8a armeabi-v7a
#TARGET_CPU_VARIANT := generic
#TARGET_CPU_VARIANT_RUNTIME := cortex-a55

#TARGET_2ND_ARCH := arm
#TARGET_2ND_ARCH_VARIANT := armv7-a-neon
#TARGET_2ND_CPU_ABI := armeabi-v7a
#TARGET_2ND_CPU_ABI2 := armeabi
#TARGET_2ND_CPU_VARIANT := generic
#TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a55

# --- Kernel (GKI2 prebuilt)
BOARD_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_IMAGE_NAME := Image.gz
TARGET_PREBUILT_KERNEL := device/ssh/NOTE_23/prebuilt/Image.gz
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_PREBUILT_DTBIMAGE_DIR := device/ssh/NOTE_23/prebuilt/dtb/
BOARD_DTB_FILE := 01_dtbdump_MT6789.dtb
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_TAGS_OFFSET := 0x07c08000
BOARD_DTB_OFFSET := 0x0bc08000

# --- Vendor boot (recovery lives here)
BOARD_USES_RECOVERY_AS_BOOT := false
BOARD_USES_VENDOR_BOOT := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true

# --- Dynamic partitions (Treble)
BOARD_SUPER_PARTITION_GROUPS := ssh_dynamic_partitions
BOARD_SSH_DYNAMIC_PARTITIONS_PARTITION_LIST := \
    system \
    system_ext \
    product \
    vendor \
    vendor_dlkm \
    odm_dlkm

BOARD_BUILD_RETROFIT_DYNAMIC_PARTITIONS := true
#BOARD_BUILD_SYSTEM_ROOT_IMAGE := false

# --- Partition sizes (⚠️ UPDATE using lpdump)
BOARD_SUPER_PARTITION_SIZE := 9663676416
BOARD_SSH_DYNAMIC_PARTITIONS_SIZE := 9663676416
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDORIMAGE_PARTITION_SIZE := 1035907072
BOARD_PRODUCTIMAGE_PARTITION_SIZE := 2677690368
BOARD_ODMIMAGE_PARTITION_SIZE := 348160

BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := ext4
#BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
# --- Filesystem support
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# --- Treble and copy-out targets
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_ODM := odm

# --- Recovery
TARGET_RECOVERY_FSTAB := device/ssh/NOTE_23/fstab.note_23
BOARD_INCLUDE_RECOVERY_DTBO := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"

# --- Verified Boot (⚠️ optional; disable if signing causes issues)
BOARD_AVB_ENABLE := false
BOARD_AVB_ALGORITHM := SHA256_RSA2048
BOARD_AVB_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem

# --- Misc
BOARD_FLASH_BLOCK_SIZE := 131072
TARGET_NO_BOOTLOADER := true
TARGET_USES_UEFI := false
SELINUX_IGNORE_NEVERALLOWS := true

# --- Security patch level (⚠️ Update when known)
VENDOR_SECURITY_PATCH := 2024-10-05
