#
# ssh NOTE 23 (G99 / MT6789)
# Board configuration file
#
include vendor/ssh/NOTE_23/BoardConfigVendor.mk

DEVICE_PATH := device/ssh/NOTE_23

BUILD_BROKEN_DUP_RULES := true

BOARD_VENDOR := ssh
TARGET_BOARD_PLATFORM := mt6789
TARGET_ARCH := arm64
TARGET_KERNEL_ARCH := arm64

TARGET_CPU_ABI := arm64-v8a
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI_LIST := arm64-v8a,armeabi-v7a
TARGET_CPU_VARIANT := cortex-a76  # Updated for MT6789
TARGET_CPU_VARIANT_RUNTIME := cortex-a55
TARGET_SUPPORTS_64_BIT_APPS := true

# --- Kernel and Boot (GKI2 Prebuilt)
BOARD_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_IMAGE_NAME := Image.gz
TARGET_PREBUILT_KERNEL := device/ssh/NOTE_23/prebuilt/Image.gz
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_PREBUILT_DTBIMAGE_DIR := device/ssh/NOTE_23/prebuilt/dtb/
BOARD_DTB_FILE := 01_dtbdump_MT6789.dtb

# CRITICAL: MTK often uses 4096. Verify this with stock boot image info.
BOARD_KERNEL_PAGESIZE := 4096 
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_TAGS_OFFSET := 0x07c08000
BOARD_DTB_OFFSET := 0x0bc08000

# --- Vendor Boot (Recovery)
BOARD_USES_VENDOR_BOOT := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true

# --- Dynamic partitions (Treble)
BOARD_SUPER_PARTITION_GROUPS := ssh_dynamic_partitions
BOARD_SSH_DYNAMIC_PARTITIONS_PARTITION_LIST := \
    system \
    system_ext \
    product \
    vendor \
    vendor_dlkm \
    odm_dlkm

# LOGICAL CORRECTION: Set to 'false' for native Treble support (API 33).
BOARD_BUILD_RETROFIT_DYNAMIC_PARTITIONS := false 

# --- A/B OTA Partitions (Required when AB_OTA_UPDATER is true)
AB_OTA_PARTITIONS += \
    boot \
    dtbo \
    odm \
    product \
    system \
    system_ext \
    vendor \
    vendor_boot \
    vendor_dlkm \
    odm_dlkm

# --- Partition sizes (⚠️ CRITICAL: MUST BE EXACT)
BOARD_SUPER_PARTITION_SIZE := 9663676416
BOARD_SSH_DYNAMIC_PARTITIONS_SIZE := 9663676416
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDORIMAGE_PARTITION_SIZE := 1035907072
BOARD_PRODUCTIMAGE_PARTITION_SIZE := 2677690368
BOARD_ODMIMAGE_PARTITION_SIZE := 348160

# --- Filesystem support
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4 
#TARGET_RECOVERY_FSTAB := $(LOCAL_PATH)/fstab.note_23
#TARGET_FSTAB := $(LOCAL_PATH)/fstab.note_23

# --- Treble and copy-out targets
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_ODM := odm

# --- Recovery (FSTAB PATH CORRECTED)
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/fstab.note_23
BOARD_INCLUDE_RECOVERY_DTBO := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"

# --- Verified Boot 
BOARD_AVB_ENABLE := false
BOARD_AVB_ALGORITHM := SHA256_RSA2048
BOARD_AVB_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem

# --- Misc
BOARD_FLASH_BLOCK_SIZE := 131072
TARGET_NO_BOOTLOADER := true
TARGET_USES_UEFI := false
SELINUX_IGNORE_NEVERALLOWS := true
VENDOR_SECURITY_PATCH := 2024-10-05
